services:
 
  haproxy:
    image: haproxy:lts
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg
    ports:
      - '8080:8080'
      - '8000:8000'
      - '8001:8001'
      - '9000:9000'
      - '9001:9001'
      - '9090:9090'
      - '3000:3000'
    volumes:
      - 'minio-replication_haproxy:/var/run/haproxy:rw'

  replica:
    image: bitnami/minio:2023.6.23
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_SKIP_CLIENT=yes
      - MINIO_SCHEME=http
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:8001
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - MINIO_PROMETHEUS_JOB_ID=replica
    volumes:
      - 'minio-replication_minio-replica_data:/data'
  minio-0:
    image: bitnami/minio:2023.6.23
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-{0...3}/data/part{0...3}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_SCHEME=http
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - MINIO_PROMETHEUS_JOB_ID=minio-cluster
    volumes:
      - 'minio-replication_minio-0_data-0:/data/part0:rw'
      - 'minio-replication_minio-0_data-1:/data/part1:rw'
      - 'minio-replication_minio-0_data-2:/data/part2:rw'
      - 'minio-replication_minio-0_data-3:/data/part3:rw'
  minio-1:
    image: bitnami/minio:2023.6.23
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-{0...3}/data/part{0...3}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_SCHEME=http
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - MINIO_PROMETHEUS_JOB_ID=minio-cluster
    volumes:
      - 'minio-replication_minio-1_data-0:/data/part0:rw'
      - 'minio-replication_minio-1_data-1:/data/part1:rw'
      - 'minio-replication_minio-1_data-2:/data/part2:rw'
      - 'minio-replication_minio-1_data-3:/data/part3:rw'
  minio-2:
    image: bitnami/minio:2023.6.23
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-{0...3}/data/part{0...3}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_SCHEME=http
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - MINIO_PROMETHEUS_JOB_ID=minio-cluster
    volumes:
      - 'minio-replication_minio-2_data-0:/data/part0:rw'
      - 'minio-replication_minio-2_data-1:/data/part1:rw'
      - 'minio-replication_minio-2_data-2:/data/part2:rw'
      - 'minio-replication_minio-2_data-3:/data/part3:rw'
  minio-3:
    image: bitnami/minio:2023.6.23
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio-{0...3}/data/part{0...3}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_SCHEME=http
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - MINIO_PROMETHEUS_JOB_ID=minio-cluster
    volumes:
      - 'minio-replication_minio-3_data-0:/data/part0:rw'
      - 'minio-replication_minio-3_data-1:/data/part1:rw'
      - 'minio-replication_minio-3_data-2:/data/part2:rw'
      - 'minio-replication_minio-3_data-3:/data/part3:rw'
  prometheus:
    image: bitnami/prometheus:2.45.0
    configs:
      - source: prometheus_config
        target: /opt/bitnami/prometheus/conf/prometheus.yml
    volumes:
      - 'minio-replication_prometheus:/opt/bitnami/prometheus/data'
  grafana:
    image: bitnami/grafana:10.0.1
    configs:
      - source: grafana_config
        target: /opt/bitnami/grafana/conf/grafana.ini
    environment:
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8080/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
  grafana-image-renderer:
    image: bitnami/grafana-image-renderer:3.7.1
    environment:
      - ENABLE_METRICS=true
  influxdb:
    image: bitnami/influxdb:2.7.1
    environment:
      - INFLUXDB_ADMIN_USER=influxdb-root-user
      - INFLUXDB_ADMIN_USER_PASSWORD=influxdb-root-password
      - INFLUXDB_ADMIN_USER_TOKEN=influxdb-root-token
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    ports:
      - '8086:8086'
      - '8088:8088'
    #volumes:
    #  - 'minio-replication_influxdb:/'

volumes:
  minio-replication_minio-0_data-0:
    external: true
  minio-replication_minio-0_data-1:
    external: true
  minio-replication_minio-0_data-2:
    external: true
  minio-replication_minio-0_data-3:
    external: true
  minio-replication_minio-1_data-0:
    external: true
  minio-replication_minio-1_data-1:
    external: true
  minio-replication_minio-1_data-2:
    external: true
  minio-replication_minio-1_data-3:
    external: true
  minio-replication_minio-2_data-0:
    external: true
  minio-replication_minio-2_data-1:
    external: true
  minio-replication_minio-2_data-2:
    external: true
  minio-replication_minio-2_data-3:
    external: true
  minio-replication_minio-3_data-0:
    external: true
  minio-replication_minio-3_data-1:
    external: true
  minio-replication_minio-3_data-2:
    external: true
  minio-replication_minio-3_data-3:
    external: true
  minio-replication_minio-replica_data:
    external: true
  minio-replication_haproxy:
    external: true
  minio-replication_prometheus:
    external: true

configs:
  haproxy_config:
    file: haproxy.cfg
  prometheus_config:
    file: prometheus.yml
  grafana_config:
    file: grafana.ini
  influxdb_config:
    file: influxdb.conf
